##### Stage 1: Build Angular Application for local backend testing
FROM node:lts-alpine AS build
WORKDIR /app

RUN apk add --no-cache brotli

COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build:local

WORKDIR /app/dist/bakery-app/browser
RUN find . -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" -o -name "*.json" -o -name "*.svg" -o -name "*.xml" -o -name "*.txt" \) -exec brotli -f -q 11 {} \;

##### Stage 2: Nginx
FROM ghcr.io/macbre/nginx-http3:latest

RUN rm -f /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/bakery-app/browser /usr/share/nginx/html
COPY config/dev/default.conf /etc/nginx/conf.d/default.conf
COPY config/prod/compression.conf /etc/nginx/conf.d/compression.conf

EXPOSE 4200
